create database bancoflor 
use bancoflor

CREATE TABLE Produtos (
  COD_PRODUTO INT PRIMARY KEY,
  QTDE INT NOT NULL,
  DESCRICAO VARCHAR(300) NOT NULL,
  VALOR FLOAT NOT NULL
)
CREATE TABLE CLIENTES( 
  COD_CLIENTE INT PRIMARY KEY,
  NOME VARCHAR(50) NOT NULL,
)
CREATE TABLE NF( 
  COD_NF INT PRIMARY KEY,
  DATE DATE NOT NULL,
  COD_CLIENTE INT NOT NULL,
  CONSTRAINT FK_NF_CLIENTES
    FOREIGN KEY (COD_CLIENTE)
    REFERENCES Clientes(COD_CLIENTE)
)
CREATE TABLE VENDAS( 
  COD_PRODUTO INT,
  COD_NF INT NOT NULL,
  QTDEVENDAS INT NOT NULL,
  CONSTRAINT PK_Vendas
    PRIMARY KEY (COD_PRODUTO, COD_NF),
  CONSTRAINT FK_Vendas_Produtos
    FOREIGN KEY (COD_PRODUTO)
    REFERENCES Produtos(COD_PRODUTO),
  CONSTRAINT FK_Vendas_NF
    FOREIGN KEY (COD_NF)
    REFERENCES NF(COD_NF)
)

SELECT Produtos.COD_PRODUTO, Produtos.QTDE, Produtos.DESCRICAO, Produtos.VALOR, Vendas.QTDEVENDAS, NF.DATE, CLIENTES.NOME
FROM Produtos
INNER JOIN Vendas ON Produtos.COD_PRODUTO = Vendas.COD_PRODUTO
INNER JOIN NF ON Vendas.COD_NF = NF.COD_NF
INNER JOIN CLIENTES ON NF.COD_CLIENTE = CLIENTES.COD_CLIENTE

INSERT INTO Produtos(COD_PRODUTO, QTDE, DESCRICAO, VALOR)
VALUES (1, 3000, 'Bromelia', 11.49)

INSERT INTO Produtos(COD_PRODUTO, QTDE, DESCRICAO, VALOR)
VALUES (2, 3000, 'Rosa', 8.49)

INSERT INTO Produtos(COD_PRODUTO, QTDE, DESCRICAO, VALOR)
VALUES (3, 9000, 'Ixora', 44.22)

INSERT INTO Produtos(COD_PRODUTO, QTDE, DESCRICAO, VALOR)
VALUES (4, 2000, 'Celosia', 8.96)

INSERT INTO Produtos(COD_PRODUTO, QTDE, DESCRICAO, VALOR)
VALUES (5, 4000, 'Helicônia', 12.50)

INSERT INTO CLIENTES(COD_CLIENTE,NOME)
VALUES(1,'Aldair Braz')

INSERT INTO CLIENTES(COD_CLIENTE,NOME)
VALUES(2,'Vinicius')

INSERT INTO CLIENTES(COD_CLIENTE,NOME)
VALUES(3,'Pestana')

INSERT INTO CLIENTES(COD_CLIENTE,NOME)
VALUES(4,'Vitral')

INSERT INTO CLIENTES(COD_CLIENTE,NOME)
VALUES(5,'Lani Miranda')

select*from Produtos
drop database bancoflor
use master